---
# Title: role-rundeck
#
# Author: bitfinity-nl
# File: tasks/rundeck.yml
#
# Description:
#   Rundeck is automated runbooks that work the way you want to work. 


- name: "Install packages"
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - apache2

- name: "Apache2 enable SSL module"
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - log_config
    - proxy
    - proxy_http
    - proxy_wstunnel
    - ssl

- name: "Transfer templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'apache2/rundeck.conf.j2', dest: '/etc/apache2/sites-available/rundeck.conf' }

- name: "Disable default sites"
  command: "a2dissite {{ item }}"
  with_items:
    - 000-default.conf
    - default-ssl.conf 
  notify:
    - restart_apache2

- name: "Enable rundeck.conf"
  command: a2ensite rundeck.conf
  notify:
    - restart_apache2

- name: "Configure Firewall"
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items:
    - "80"
    - "443"