---
# Title: role-rundeck
#
# Author: bitfinity-nl
# File: tasks/mariadb.yml
#
# Description:
#   Rundeck is automated runbooks that work the way you want to work.


- name: "Add the MariaDB GPG key to this system"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"

- name: "Add repository"
  apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] http://ftp.utexas.edu/mariadb/repo/10.4/ubuntu bionic main
    state: present
    filename: maria-db-10.4

- name: "Set mariadb root password before installing"
  debconf:
    name: mariadb-server
    question: "{{ item }}"
    vtype: password
    value: "{{ mariadb_administrative_password }}"
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again

- name: "Install packages"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes 
  vars:
    packages:
    - mariadb-server
    - mariadb-client
    - mariadb-common
    - python-mysqldb

- name: "Deletes anonymous MySQL server user for localhost"
  mysql_user:
    user: ""
    state: absent
    login_user: root
    login_password: "{{ mariadb_administrative_password }}"

- name: "Secures the MySQL root user"
  mysql_user:
    user: root
    password: "{{ mariadb_administrative_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{mariadb_administrative_password }}"
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"